theme = "modern"
icons = "material-nf"

[[block]]
block = "apt"

[[block]]
block = "disk_space"
path = "/"
info_type = "available"
unit = "GB"
interval = 20
warning = 20.0
alert = 10.0

[[block]]
block = "memory"
display_type = "memory"

[[block]]
block = "cpu"

[[block]]
block = "load"
interval = 5

[[block]]
block = "temperature"

[[block]]
block = "sound"
driver = "pulseaudio"

[[block]]
block = "backlight"

[[block]]
block = "time"
interval = 5
format = "%a %d/%m %R"

[[block]]
block = "battery"

